### ISSUE TITLE
An incorrect key for me in the UK script

### ISSUE THREAD

**Issue by wmoindrot** [davidebreso/mkeyb#6]
Thank you @davidebreso and also to Tom Ehlert for this project. 

I want to use it on an IBM 486 with a Model M keyboard (1391406) but I am finding that the period (.) key that sits at the bottom of the numeric keypad on the right hand side of the keyboard is returning a comma (,) in dos. 

All else seems ok. I am running I think the 052 build, I need to check tomorrow that I'm not on 0.39. I don't know if my keyboard is pumping some weird code out of if it is the receiving computer but the original KeyB was ok, and also trying xkeyb this also is ok with the UK argument. I have had a quick look into the mkeyb.txt and this would be my next step I guess, it seems like not an index for every key is provided/needed - any pointers for changing the definition of this key? It seems that the original KeyB resolutely loads two copies so keen to use this svelte tool. Thanks again, Will

**Comment by davidebreso** [comment]
Hi @wmoindrot,
getting a comma (,) instead of a dot with the numpad is the expected behaviour of release 052, and possilby also earliear ones. The keyboard mapping was defined in that way in the code. However, your experience and a check with the MSDOS keyboard layout showed that was not correct. I fixed the keyboard mapping with commit 7fcc815f2da1d488a2a764b114b86af3fb997e4c

The fixed version of MKEYB.EXE is here: [github.com/davidebreso/mkeyb/raw/7fcc815f2da1d488a2a764b114b86af3fb997e4c/mkeyb.exe](github.com/davidebreso/mkeyb/raw/7fcc815f2da1d488a2a764b114b86af3fb997e4c/mkeyb.exe)

**Comment by Bloodbat** [comment]
This problem also affects the Spanish keyboard.

**Comment by davidebreso** [comment]
Thank you @Bloodbat. The spanish layout was affected by the bug as well. I checked all layouts and now they should be correct, at least for the ones that are also included in MSDOS. Commit https://github.com/davidebreso/mkeyb/commit/72358c4ab67c06e3a4ae395b6d83b366c6ed5188 fixes the bug

**Comment by wmoindrot** [comment]
Thanks @davidebreso, I  got round to testing this and now working nicely on my PC  (back to a dot instead of a comma) and 0.5k instead of 2.5k of lower ram
